const client = require('./client');
const clients = require('./clients');
const attachments = require('./attachments');
const adminSessions = require('./adminSessions');
const inquiries = require('./inquiries');
const projects = require('./projects');
const portal = require('./portal');
const proposals = require('./proposals');
const proposalShares = require('./proposalShares');

module.exports = {
  getDb: client.getDb,
  closeDb: client.closeDb,
  runMigrations: client.runMigrations,
  backfillClients: clients.backfillClients,
  findClientByEmail: clients.findClientByEmail,
  createClient: clients.createClient,
  setInquiryClientId: clients.setInquiryClientId,
  resolveClientForInquiry: clients.resolveClientForInquiry,
  listAdminClients: clients.listAdminClients,
  getAdminClientById: clients.getAdminClientById,
  insertAttachments: attachments.insertAttachments,
  listAttachmentsForInquiry: attachments.listAttachmentsForInquiry,
  getAdminAttachment: attachments.getAdminAttachment,
  deleteAttachmentById: attachments.deleteAttachmentById,
  createSession: adminSessions.createSession,
  getSessionByTokenHash: adminSessions.getSessionByTokenHash,
  touchSession: adminSessions.touchSession,
  deleteSessionByTokenHash: adminSessions.deleteSessionByTokenHash,
  deleteExpiredSessions: adminSessions.deleteExpiredSessions,
  deleteSessionsByFingerprint: adminSessions.deleteSessionsByFingerprint,
  backfillInquiryPipeline: inquiries.backfillInquiryPipeline,
  syncInquiryPipeline: inquiries.syncInquiryPipeline,
  markInquiryContacted: inquiries.markInquiryContacted,
  insertInquiry: inquiries.insertInquiry,
  updateNotificationStatus: inquiries.updateNotificationStatus,
  getInquiryWithAttachments: inquiries.getInquiryWithAttachments,
  listAdminInquiries: inquiries.listAdminInquiries,
  getAdminInquiryById: inquiries.getAdminInquiryById,
  createProject: projects.createProject,
  updateProjectStatus: projects.updateProjectStatus,
  updateProjectDomain: projects.updateProjectDomain,
  getProjectById: projects.getProjectById,
  getProjectByProposalId: projects.getProjectByProposalId,
  getProjectForInquiry: projects.getProjectForInquiry,
  getAdminProjectById: projects.getAdminProjectById,
  listAdminProjects: projects.listAdminProjects,
  issuePortalSetupToken: portal.issuePortalSetupToken,
  getProjectForPortalSetup: portal.getProjectForPortalSetup,
  completePortalPasswordSetup: portal.completePortalPasswordSetup,
  hashPortalSetupToken: portal.hashPortalSetupToken,
  createClientSession: portal.createClientSession,
  getClientSessionByTokenHash: portal.getClientSessionByTokenHash,
  touchClientSession: portal.touchClientSession,
  deleteClientSessionByTokenHash: portal.deleteClientSessionByTokenHash,
  deleteExpiredClientSessions: portal.deleteExpiredClientSessions,
  deleteClientSessionsForProject: portal.deleteClientSessionsForProject,
  getPortalProjectBundle: portal.getPortalProjectBundle,
  acceptProposal: proposals.acceptProposal,
  declineProposal: proposals.declineProposal,
  requestProposalRevision: proposals.requestProposalRevision,
  listRevisionRequestsForProposal: proposals.listRevisionRequestsForProposal,
  createProposal: proposals.createProposal,
  updateProposal: proposals.updateProposal,
  markProposalSent: proposals.markProposalSent,
  getProposalById: proposals.getProposalById,
  listProposalsByInquiryId: proposals.listProposalsByInquiryId,
  listAdminProposals: proposals.listAdminProposals,
  createProposalShare: proposalShares.createProposalShare,
  prepareProposalShareToken: proposalShares.prepareProposalShareToken,
  deleteSharesForProposal: proposalShares.deleteSharesForProposal,
  getProposalShareByRawToken: proposalShares.getProposalShareByRawToken,
  hashShareToken: proposalShares.hashShareToken,
};
