export const workHistory = [
  {
    id: 4,
    title: 'Fullstack Engineer',
    company: 'CoreCare',
    dates: 'Oct 2024 - Nov 2024',
    summary: [
      `Assisted with the development of a HIPAA-compliant mobile web application for Medicaid and insurance workflow management in long-term care facilities`,
      `Designed scalable backend architectures optimized for mobile experiences and data integration`,
      `Implemented secure, HIPAA-compliant solutions ensuring data privacy and protection`,
      `Collaborated with frontend engineers, Product Management, and UX teams to deliver a high-performance, user-friendly application`,
      `Optimized application performance and security, focusing on creating an intuitive experience for long-term care professionals`,
      `Continuously improved codebase, implementing best practices in architecture and deployment using AWS and other cloud technologies`,
    ],
    link: 'https://corecare.ai/',
  },
  {
    id: 4,
    title: 'Fullstack Engineer',
    company: 'Envoy Technologies',
    dates: 'Oct 2022 - Jul 2024',
    summary: [
      ` Assisted with developing and deploying a MVP with a tight deadline`,
      `Made significant changes to the existing admin portal`,
      `Sole developer in charge of the creation of a customer-facing portal`,
      `Development of new user-facing features using React.js`,
      `Built reusable components and front-end libraries for future use`,
      `API management and new feature implementations (Node.js/Express)`,
      `API Integrations with third party services`,
      `Translation of designs and wireframes into high-quality code`,
      `Optimization of components for maximum performance across a vast array of web-capable devices and browsers`,
      `Participation in scrum ceremonies daily to uphold the agile methodology`,
      `Upheld best QA practices with code reviews, unit testing, and maintaining high code standards`,
    ],
    link: 'https://www.envoythere.com/',
  },
  {
    id: 3,
    title: 'Freelance Web Developer',
    company: 'Yes Devil Band',
    dates: 'Apr 2018 - Sep 2022',
    summary: [
      `Created an extensive online web application (with React)
       for a band to showcase music, events, photos, videos, and more`,
      `Features an online store with dynamic shopping cart functionality and secure payments with the Stripe API`,
      `Developed reusable React components, using Redux and Context for state management`,
      `Coordinated with client to design a custom interactive audio player with a track list,
       album cover, lyrics, and links to popular streaming services (built with React)`,
      `Designed and allocated interactive flyers and promotional banners on the site
        for upcoming concerts and events`,
      `Implemented User Edit functionality, allowing a user to authenticate themselves through Microsoft Azure OAuth 2.0 flow using the band’s email credentials, and continue to the site in “Edit Mode”`,
      `User can create, edit, or delete Upcoming Shows and Current Members`,
      `Forms made with React Final Form`,
      `Image/File Upload with multer`,
      `Node.js/Express backend, data stored with MongoDB and mongoose`,
      `CI/CD with GitHub Actions`,
      `Site hosted on DigitalOcean server block using NGINX reverse proxy, uses PM2 process manager for production Node.js applications`,
    ],
    link: 'https://yesdevil.com/',
  },
  {
    id: 2,
    title: 'Freelance Web Developer',
    company: 'Barsell Construction',
    dates: 'Jul 2017 - Feb 2020',
    summary: [
      `Developed a full responsive website from start to finish using HTML, CSS, JavaScript, and jQuery`,
      `Participated in design and development sessions with client team to understand the requirements`,
      `Created a custom logo to compliment the brand and company catch phrase`,
      `Google Maps API`,
      `Images optimized, reducing page load time and improving user experience`,
      `Organized work flow with GitHub`,
      `Configured domain, hosted site on Digital Ocean droplet using Nginx Reverse Proxy`,
    ],
    link: 'https://barsellconstruction.com/',
  },
  {
    id: 1,
    title: 'Freelance Web Developer',
    company: 'Fawkes Home Solutions',
    dates: 'Dec 2019 - Jan 2020',
    summary: [
      `Designed, developed, and deployed mobile friendly website with interactive features
       to optimize traffic, increase page views, and enhance site stickiness`,
      `Formulated designs that expanded upon the brand, accenting key focus points of the business model`,
      `Developed a dynamic and interactive website with a comfortable user experience (UX)`,
      `Wrote maintainable and extensible code, utilizing GitHub to optimize and organize workflow`,
      `Configured domain, hosted site on Digital Ocean droplet using Nginx Reverse Proxy`,
    ],
    link: 'https://www.fawkeshomesolutions.com/',
  },
  {
    id: 0,
    title: 'Freelance Web Developer',
    company: 'The Color Six Band',
    dates: 'May 2019 - Jul 2019',
    summary: [
      `Custom band website with HTML, CSS, and JavaScript (jQuery), running on a Node.js/Express server`,
      `Utilizes a customizable audio player plugin`,
      `Created a custom seamless and responsive photo gallery with images of various
       sizes and ratios`,
      `Uses SongKick, a widget that let the user update events from their dashboard and
      have it update automatically on their website`,
      `Organized work flow with GitHub`,
      `Configured domain, hosted site on Digital Ocean droplet using Nginx Reverse Proxy`,
    ],
    link: 'https://the-color-six.herokuapp.com/',
  },
];

export default { workHistory };
